//! The status window's freedesktop launcher: a `.desktop` file and hicolor
//! icons under `$XDG_DATA_HOME`, so `cued-gui` appears in the applications
//! list and the dock shows its icon. `cued-gui --install-desktop` writes it;
//! `cued uninstall` removes it. An entry this code didn't write is never
//! replaced or removed.
use std::io::Write;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};

use crate::paths::Paths;

const MARKER: &str = "# Generated by cued-gui --install-desktop\n";
/// Matches the window's Wayland app_id and X11 WM_CLASS, which is how a
/// dock pairs a running window with this entry.
pub const APP_ID: &str = "cued";

/// One bundled icon: its hicolor size directory (`64x64`, `scalable`) and bytes.
pub struct Icon {
    pub size: &'static str,
    pub bytes: &'static [u8],
}

/// The icon sizes [`remove`] cleans up: the window's bundled set.
pub const SIZES: [&str; 7] = [
    "16x16", "32x32", "64x64", "128x128", "256x256", "512x512", "scalable",
];

/// `$XDG_DATA_HOME`: the parent of cued's own data directory.
fn data_home(paths: &Paths) -> Result<&Path> {
    paths
        .data_dir
        .parent()
        .context("the data directory has no parent")
}

pub fn entry_path(paths: &Paths) -> Result<PathBuf> {
    Ok(data_home(paths)?.join(format!("applications/{APP_ID}.desktop")))
}

fn icon_theme(paths: &Paths) -> Result<PathBuf> {
    Ok(data_home(paths)?.join("icons/hicolor"))
}

fn icon_path(paths: &Paths, size: &str) -> Result<PathBuf> {
    let extension = if size == "scalable" { "svg" } else { "png" };
    Ok(icon_theme(paths)?.join(format!("{size}/apps/{APP_ID}.{extension}")))
}

/// Quote one Exec argument per the Desktop Entry spec: reserved characters
/// are backslash-escaped inside double quotes, then the value as a whole
/// escapes backslashes again, and `%` is doubled so it is not a field code.
fn quote_exec(value: &str) -> Result<String> {
    if value.chars().any(char::is_control) {
        bail!("desktop entry values cannot contain control characters");
    }
    let mut quoted = String::from("\"");
    for c in value.chars() {
        match c {
            '"' | '`' | '$' => quoted.extend(['\\', c]),
            '\\' => quoted.push_str("\\\\\\\\"),
            '%' => quoted.push_str("%%"),
            c => quoted.push(c),
        }
    }
    quoted.push('"');
    Ok(quoted)
}

/// The entry launches `executable` by absolute path: a desktop session's
/// launcher often lacks `~/.cargo/bin` on its PATH.
pub fn render(executable: &Path) -> Result<String> {
    if !executable.is_absolute() {
        bail!("the window's executable path must be absolute");
    }
    let exec = quote_exec(
        executable
            .to_str()
            .context("desktop entry paths must be UTF-8")?,
    )?;
    Ok(format!(
        "[Desktop Entry]\n{MARKER}Type=Application\nName=cued\n\
         Comment=What your scheduled jobs are running, waiting on, and finished\n\
         Exec={exec}\nIcon={APP_ID}\nTerminal=false\nCategories=System;Monitor;\n\
         Keywords=jobs;runs;schedule;pipeline;cron;\nStartupNotify=true\n\
         StartupWMClass={APP_ID}\n"
    ))
}

/// What occupies [`entry_path`].
#[derive(Debug, PartialEq, Eq)]
pub enum Entry {
    Absent,
    Generated,
    /// Someone else's entry, which is never replaced or removed.
    Custom,
}

pub fn read_entry(paths: &Paths) -> Result<Entry> {
    match std::fs::read_to_string(entry_path(paths)?) {
        Ok(text) if text.contains(MARKER) => Ok(Entry::Generated),
        Ok(_) => Ok(Entry::Custom),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(Entry::Absent),
        // Unreadable or not UTF-8: not ours.
        Err(_) => Ok(Entry::Custom),
    }
}

/// Write the icons, then the entry atomically, so a launcher watching the
/// directory never sees an entry whose icon is missing. Returns the entry path.
pub fn install(paths: &Paths, executable: &Path, icons: &[Icon]) -> Result<PathBuf> {
    let entry = render(executable)?;
    let target = entry_path(paths)?;
    if read_entry(paths)? == Entry::Custom {
        bail!(
            "refusing to replace {}: not one cued-gui installed",
            target.display()
        );
    }
    for icon in icons {
        let path = icon_path(paths, icon.size)?;
        let dir = path.parent().context("icon path has no parent")?;
        std::fs::create_dir_all(dir).with_context(|| format!("creating {}", dir.display()))?;
        std::fs::write(&path, icon.bytes).with_context(|| format!("writing {}", path.display()))?;
    }
    refresh_icon_cache(paths)?;
    let dir = target.parent().context("entry path has no parent")?;
    std::fs::create_dir_all(dir).with_context(|| format!("creating {}", dir.display()))?;
    // Written beside the target and renamed over it: never half an entry.
    let temp = dir.join(format!(".{APP_ID}.desktop.{}", std::process::id()));
    let written = (|| -> std::io::Result<()> {
        use std::os::unix::fs::OpenOptionsExt;
        let mut file = std::fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            // Entries are conventionally world-readable.
            .mode(0o644)
            .open(&temp)?;
        file.write_all(entry.as_bytes())?;
        file.sync_all()?;
        std::fs::rename(&temp, &target)
    })();
    if let Err(error) = written {
        let _ = std::fs::remove_file(&temp);
        return Err(error).with_context(|| format!("writing {}", target.display()));
    }
    Ok(target)
}

/// Delete the generated entry and its icons. Returns the removed entry, or
/// `None` when there was none to remove; a custom entry and its icons are left.
pub fn remove(paths: &Paths) -> Result<Option<PathBuf>> {
    let target = entry_path(paths)?;
    if read_entry(paths)? != Entry::Generated {
        return Ok(None);
    }
    std::fs::remove_file(&target).with_context(|| format!("removing {}", target.display()))?;
    for size in SIZES {
        let path = icon_path(paths, size)?;
        match std::fs::remove_file(&path) {
            Err(error) if error.kind() != std::io::ErrorKind::NotFound => {
                return Err(error).with_context(|| format!("removing {}", path.display()));
            }
            _ => {}
        }
    }
    refresh_icon_cache(paths)?;
    Ok(Some(target))
}

/// GTK trusts an existing `icon-theme.cache` over the directory, so a stale
/// one hides new icons and keeps removed ones. Without a cache there is
/// nothing to do. Best effort: the tool may be absent.
fn refresh_icon_cache(paths: &Paths) -> Result<()> {
    let theme = icon_theme(paths)?;
    if theme.join("icon-theme.cache").exists() {
        let _ = std::process::Command::new("gtk-update-icon-cache")
            .args(["-f", "-t", "-q"])
            .arg(&theme)
            .stdin(std::process::Stdio::null())
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .status();
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn paths(root: &Path) -> Paths {
        Paths {
            data_dir: root.join("share/cued"),
            db_file: root.join("share/cued/cued.db"),
            lock_file: root.join("share/cued/cued.lock"),
            logs_dir: root.join("share/cued/logs"),
            daemon_log: root.join("share/cued/daemon.log"),
            socket_file: root.join("cued.sock"),
            config_file: root.join("config/cued/config.toml"),
        }
    }

    #[test]
    fn exec_quoting_escapes_reserved_characters_and_rejects_newlines() {
        assert_eq!(quote_exec("/a b/c").unwrap(), "\"/a b/c\"");
        assert_eq!(
            quote_exec("/x\"$`%\\y").unwrap(),
            "\"/x\\\"\\$\\`%%\\\\\\\\y\""
        );
        assert!(quote_exec("/x\nExec=evil").is_err());
        assert!(render(Path::new("relative")).is_err());
    }

    #[test]
    fn install_and_remove_round_trip_and_spare_custom_entries() {
        let root = tempfile::tempdir().unwrap();
        let paths = paths(root.path());
        let icons = [
            Icon {
                size: "64x64",
                bytes: b"png",
            },
            Icon {
                size: "scalable",
                bytes: b"<svg/>",
            },
        ];
        let entry = install(&paths, Path::new("/opt/bin/cued-gui"), &icons).unwrap();
        assert_eq!(entry, root.path().join("share/applications/cued.desktop"));
        let text = std::fs::read_to_string(&entry).unwrap();
        assert!(text.contains("Exec=\"/opt/bin/cued-gui\"\n"), "{text}");
        assert!(text.contains("StartupWMClass=cued\n"), "{text}");
        let icon = root
            .path()
            .join("share/icons/hicolor/scalable/apps/cued.svg");
        assert_eq!(std::fs::read(&icon).unwrap(), b"<svg/>");
        use std::os::unix::fs::PermissionsExt;
        let mode = std::fs::metadata(&entry).unwrap().permissions().mode();
        assert_eq!(mode & 0o777, 0o644);
        // Reinstalling replaces our own entry.
        install(&paths, Path::new("/usr/bin/cued-gui"), &icons).unwrap();

        assert_eq!(remove(&paths).unwrap(), Some(entry.clone()));
        assert!(!entry.exists() && !icon.exists());
        assert_eq!(remove(&paths).unwrap(), None);

        // Someone else's entry under our name is never touched.
        std::fs::write(&entry, "[Desktop Entry]\nName=Mine\n").unwrap();
        assert!(install(&paths, Path::new("/opt/bin/cued-gui"), &icons).is_err());
        assert_eq!(remove(&paths).unwrap(), None);
        assert!(entry.exists());
    }
}
